name: jupyter-rise
channels:
  - conda-forge
  - dlr-sc
dependencies:
  - python=3.5
  - pip
  - tigl3
  - numpy
  - jupyter
  - pythreejs
  - rise
  - pip:
    - jupyter-contrib-nbextensions
